# Generated by Django 4.0.4 on 2022-04-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Movies',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='alias',
            new_name='director',
        ),
    ]
