# Generated by Django 4.0.4 on 2022-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('adventure', 'adventure'), ('comedy', 'comedy'), ('crime', 'crime'), ('drama', 'drama'), ('musical', 'musical'), ('horror', 'horror'), ('sci-fi', 'sci-fi'), ('thriller', 'thriller')], default='n/a', max_length=10),
        ),
    ]
